"""add_logo_and_template_to_organizations

Revision ID: 375c6461dd68
Revises: c3d9e4259a99
Create Date: 2026-05-20 17:40:33.859930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '375c6461dd68'
down_revision: Union[str, None] = 'c3d9e4259a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('organizations', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('document_template', sa.String(length=20), nullable=True))
    op.execute("UPDATE organizations SET document_template = 'classic' WHERE document_template IS NULL")
    op.alter_column('organizations', 'document_template', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'document_template')
    op.drop_column('organizations', 'logo_url')
    # ### end Alembic commands ###
