"""add_etims_fields

Revision ID: da817823e711
Revises: 375c6461dd68
Create Date: 2026-05-20 17:49:35.960406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da817823e711'
down_revision: Union[str, None] = '375c6461dd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('etims_cu_invoice_no', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('etims_rcpt_sign', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('etims_int_data', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('etims_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('etims_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE organizations SET etims_enabled = FALSE WHERE etims_enabled IS NULL")
    op.alter_column('organizations', 'etims_enabled', nullable=False)
    op.add_column('organizations', sa.Column('etims_branch_id', sa.String(length=10), nullable=True))
    op.add_column('organizations', sa.Column('etims_device_serial', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('etims_auth_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'etims_auth_token')
    op.drop_column('organizations', 'etims_device_serial')
    op.drop_column('organizations', 'etims_branch_id')
    op.drop_column('organizations', 'etims_enabled')
    op.drop_column('invoices', 'etims_submitted_at')
    op.drop_column('invoices', 'etims_int_data')
    op.drop_column('invoices', 'etims_rcpt_sign')
    op.drop_column('invoices', 'etims_cu_invoice_no')
    # ### end Alembic commands ###
